module("simple cube movements");
test("(no moves)",function(){
	var cube = new Cube();
	faceTest(cube, [
		[
			 ["White","White","White"]
			,["White","White","White"]
			,["White","White","White"]
		],[
			 ["Orange","Orange","Orange"]
			,["Orange","Orange","Orange"]
			,["Orange","Orange","Orange"]
		],[
			 ["Yellow","Yellow","Yellow"]
			,["Yellow","Yellow","Yellow"]
			,["Yellow","Yellow","Yellow"]
		],[
			 ["Red","Red","Red"]
			,["Red","Red","Red"]
			,["Red","Red","Red"]
		],[
			 ["Green","Green","Green"]
			,["Green","Green","Green"]
			,["Green","Green","Green"]
		],[
			 ["Blue","Blue","Blue"]
			,["Blue","Blue","Blue"]
			,["Blue","Blue","Blue"]
		]
	]);
});
test("(no moves) (numeric)",function(){
	var cube = new Cube(true);
	faceTest(cube, [
		[
			 [0,1,2]
			,[3,4,5]
			,[6,7,8]
		],[
			 [9,10,11]
			,[12,13,14]
			,[15,16,17]
		],[
			 [18,19,20]
			,[21,22,23]
			,[24,25,26]
		],[
			 [27,28,29]
			,[30,31,32]
			,[33,34,35]
		],[
			 [36,37,38]
			,[39,40,41]
			,[42,43,44]
		],[
			 [45,46,47]
			,[48,49,50]
			,[51,52,53]
		]
	],true);
});
test("F",function(){
	var cube = new Cube();
	cube.rotate(0,true);
	faceTest(cube, [
		[
			 ["White","White","White"]
			,["White","White","White"]
			,["White","White","White"]
		],[
			 ["Green","Orange","Orange"]
			,["Green","Orange","Orange"]
			,["Green","Orange","Orange"]
		],[
			 ["Yellow","Yellow","Yellow"]
			,["Yellow","Yellow","Yellow"]
			,["Yellow","Yellow","Yellow"]
		],[
			 ["Red","Red","Blue"]
			,["Red","Red","Blue"]
			,["Red","Red","Blue"]
		],[
			 ["Green","Green","Green"]
			,["Green","Green","Green"]
			,["Red","Red","Red"]
		],[
			 ["Orange","Orange","Orange"]
			,["Blue","Blue","Blue"]
			,["Blue","Blue","Blue"]
		]
	]);
});
test("F (numeric)",function(){
	var cube = new Cube(true);
	cube.rotate(0,true);
	faceTest(cube, [
		[
			 [6,3,0]
			,[7,4,1]
			,[8,5,2]
		],[
			 [42,10,11]
			,[43,13,14]
			,[44,16,17]
		],[
			 [18,19,20]
			,[21,22,23]
			,[24,25,26]
		],[
			 [27,28,45]
			,[30,31,46]
			,[33,34,47]
		],[
			 [36,37,38]
			,[39,40,41]
			,[35,32,29]
		],[
			 [15,12,9]
			,[48,49,50]
			,[51,52,53]
		]
	],true);
});
test("F\'",function(){
	var cube = new Cube();
	cube.rotate(0,false);
	faceTest(cube, [
		[
			 ["White","White","White"]
			,["White","White","White"]
			,["White","White","White"]
		],[
			 ["Blue","Orange","Orange"]
			,["Blue","Orange","Orange"]
			,["Blue","Orange","Orange"]
		],[
			 ["Yellow","Yellow","Yellow"]
			,["Yellow","Yellow","Yellow"]
			,["Yellow","Yellow","Yellow"]
		],[
			 ["Red","Red","Green"]
			,["Red","Red","Green"]
			,["Red","Red","Green"]
		],[
			 ["Green","Green","Green"]
			,["Green","Green","Green"]
			,["Orange","Orange","Orange"]
		],[
			 ["Red","Red","Red"]
			,["Blue","Blue","Blue"]
			,["Blue","Blue","Blue"]
		]
	]);
});
test("F\' (numeric)",function(){
	var cube = new Cube(true);
	cube.rotate(0,false);
	faceTest(cube, [
		[
			 [2,5,8]
			,[1,4,7]
			,[0,3,6]
		],[
			 [47,10,11]
			,[46,13,14]
			,[45,16,17]
		],[
			 [18,19,20]
			,[21,22,23]
			,[24,25,26]
		],[
			 [27,28,44]
			,[30,31,43]
			,[33,34,42]
		],[
			 [36,37,38]
			,[39,40,41]
			,[9,12,15]
		],[
			 [29,32,35]
			,[48,49,50]
			,[51,52,53]
		]
	],true);
});
test("R",function(){
	var cube = new Cube();
	cube.rotate(1,true);
	faceTest(cube, [
		[
			 ["White","White","Blue"]
			,["White","White","Blue"]
			,["White","White","Blue"]
		],[
			 ["Orange","Orange","Orange"]
			,["Orange","Orange","Orange"]
			,["Orange","Orange","Orange"]
		],[
			 ["Green","Yellow","Yellow"]
			,["Green","Yellow","Yellow"]
			,["Green","Yellow","Yellow"]
		],[
			 ["Red","Red","Red"]
			,["Red","Red","Red"]
			,["Red","Red","Red"]
		],[
			 ["Green","Green","White"]
			,["Green","Green","White"]
			,["Green","Green","White"]
		],[
			 ["Blue","Blue","Yellow"]
			,["Blue","Blue","Yellow"]
			,["Blue","Blue","Yellow"]
		]
	]);
});
test("R (numeric)",function(){
	var cube = new Cube(true);
	cube.rotate(1,true);
	faceTest(cube, [
		[
			 [0,1,47]
			,[3,4,50]
			,[6,7,53]
		],[
			 [15,12,9]
			,[16,13,10]
			,[17,14,11]
		],[
			 [44,19,20]
			,[41,22,23]
			,[38,25,26]
		],[
			 [27,28,29]
			,[30,31,32]
			,[33,34,35]
		],[
			 [36,37,2]
			,[39,40,5]
			,[42,43,8]
		],[
			 [45,46,24]
			,[48,49,21]
			,[51,52,18]
		]
	],true);
});
test("R\'",function(){
	var cube = new Cube();
	cube.rotate(1,false);
	faceTest(cube, [
		[
			 ["White","White","Green"]
			,["White","White","Green"]
			,["White","White","Green"]
		],[
			 ["Orange","Orange","Orange"]
			,["Orange","Orange","Orange"]
			,["Orange","Orange","Orange"]
		],[
			 ["Blue","Yellow","Yellow"]
			,["Blue","Yellow","Yellow"]
			,["Blue","Yellow","Yellow"]
		],[
			 ["Red","Red","Red"]
			,["Red","Red","Red"]
			,["Red","Red","Red"]
		],[
			 ["Green","Green","Yellow"]
			,["Green","Green","Yellow"]
			,["Green","Green","Yellow"]
		],[
			 ["Blue","Blue","White"]
			,["Blue","Blue","White"]
			,["Blue","Blue","White"]
		]
	]);
});
test("R\' (numeric)",function(){
	var cube = new Cube(true);
	cube.rotate(1,false);
	faceTest(cube, [
		[
			 [0,1,38]
			,[3,4,41]
			,[6,7,44]
		],[
			 [11,14,17]
			,[10,13,16]
			,[9,12,15]
		],[
			 [53,19,20]
			,[50,22,23]
			,[47,25,26]
		],[
			 [27,28,29]
			,[30,31,32]
			,[33,34,35]
		],[
			 [36,37,24]
			,[39,40,21]
			,[42,43,18]
		],[
			 [45,46,2]
			,[48,49,5]
			,[51,52,8]
		]
	],true);
});
test("B",function(){
	var cube = new Cube();
	cube.rotate(2,true);
	faceTest(cube, [
		[
			 ["White","White","White"]
			,["White","White","White"]
			,["White","White","White"]
		],[
			 ["Orange","Orange","Blue"]
			,["Orange","Orange","Blue"]
			,["Orange","Orange","Blue"]
		],[
			 ["Yellow","Yellow","Yellow"]
			,["Yellow","Yellow","Yellow"]
			,["Yellow","Yellow","Yellow"]
		],[
			 ["Green","Red","Red"]
			,["Green","Red","Red"]
			,["Green","Red","Red"]
		],[
			 ["Orange","Orange","Orange"]
			,["Green","Green","Green"]
			,["Green","Green","Green"]
		],[
			 ["Blue","Blue","Blue"]
			,["Blue","Blue","Blue"]
			,["Red","Red","Red"]
		]
	]);
});
test("B (numeric)",function(){
	var cube = new Cube(true);
	cube.rotate(2,true);
	faceTest(cube, [
		[
			 [0,1,2]
			,[3,4,5]
			,[6,7,8]
		],[
			 [9,10,53]
			,[12,13,52]
			,[15,16,51]
		],[
			 [24,21,18]
			,[25,22,19]
			,[26,23,20]
		],[
			 [38,28,29]
			,[37,31,32]
			,[36,34,35]
		],[
			 [11,14,17]
			,[39,40,41]
			,[42,43,44]
		],[
			 [45,46,47]
			,[48,49,50]
			,[27,30,33]
		]
	],true);
});
test("B\'",function(){
	var cube = new Cube();
	cube.rotate(2,false);
	faceTest(cube, [
		[
			 ["White","White","White"]
			,["White","White","White"]
			,["White","White","White"]
		],[
			 ["Orange","Orange","Green"]
			,["Orange","Orange","Green"]
			,["Orange","Orange","Green"]
		],[
			 ["Yellow","Yellow","Yellow"]
			,["Yellow","Yellow","Yellow"]
			,["Yellow","Yellow","Yellow"]
		],[
			 ["Blue","Red","Red"]
			,["Blue","Red","Red"]
			,["Blue","Red","Red"]
		],[
			 ["Red","Red","Red"]
			,["Green","Green","Green"]
			,["Green","Green","Green"]
		],[
			 ["Blue","Blue","Blue"]
			,["Blue","Blue","Blue"]
			,["Orange","Orange","Orange"]
		]
	]);
});
test("B\' (numeric)",function(){
	var cube = new Cube(true);
	cube.rotate(2,false);
	faceTest(cube, [
		[
			 [0,1,2]
			,[3,4,5]
			,[6,7,8]
		],[
			 [9,10,36]
			,[12,13,37]
			,[15,16,38]
		],[
			 [20,23,26]
			,[19,22,25]
			,[18,21,24]
		],[
			 [51,28,29]
			,[52,31,32]
			,[53,34,35]
		],[
			 [33,30,27]
			,[39,40,41]
			,[42,43,44]
		],[
			 [45,46,47]
			,[48,49,50]
			,[17,14,11]
		]
	],true);
});
test("L",function(){
	var cube = new Cube();
	cube.rotate(3,true);
	faceTest(cube, [
		[
			 ["Green","White","White"]
			,["Green","White","White"]
			,["Green","White","White"]
		],[
			 ["Orange","Orange","Orange"]
			,["Orange","Orange","Orange"]
			,["Orange","Orange","Orange"]
		],[
			 ["Yellow","Yellow","Blue"]
			,["Yellow","Yellow","Blue"]
			,["Yellow","Yellow","Blue"]
		],[
			 ["Red","Red","Red"]
			,["Red","Red","Red"]
			,["Red","Red","Red"]
		],[
			 ["Yellow","Green","Green"]
			,["Yellow","Green","Green"]
			,["Yellow","Green","Green"]
		],[
			 ["White","Blue","Blue"]
			,["White","Blue","Blue"]
			,["White","Blue","Blue"]
		]
	]);
});
test("L (numeric)",function(){
	var cube = new Cube(true);
	cube.rotate(3,true);
	faceTest(cube, [
		[
			 [36,1,2]
			,[39,4,5]
			,[42,7,8]
		],[
			 [9,10,11]
			,[12,13,14]
			,[15,16,17]
		],[
			 [18,19,51]
			,[21,22,48]
			,[24,25,45]
		],[
			 [33,30,27]
			,[34,31,28]
			,[35,32,29]
		],[
			 [26,37,38]
			,[23,40,41]
			,[20,43,44]
		],[
			 [0,46,47]
			,[3,49,50]
			,[6,52,53]
		]
	],true);
});
test("L\'",function(){
	var cube = new Cube();
	cube.rotate(3,false);
	faceTest(cube, [
		[
			 ["Blue","White","White"]
			,["Blue","White","White"]
			,["Blue","White","White"]
		],[
			 ["Orange","Orange","Orange"]
			,["Orange","Orange","Orange"]
			,["Orange","Orange","Orange"]
		],[
			 ["Yellow","Yellow","Green"]
			,["Yellow","Yellow","Green"]
			,["Yellow","Yellow","Green"]
		],[
			 ["Red","Red","Red"]
			,["Red","Red","Red"]
			,["Red","Red","Red"]
		],[
			 ["White","Green","Green"]
			,["White","Green","Green"]
			,["White","Green","Green"]
		],[
			 ["Yellow","Blue","Blue"]
			,["Yellow","Blue","Blue"]
			,["Yellow","Blue","Blue"]
		]
	]);
});
test("L\' (numeric)",function(){
	var cube = new Cube(true);
	cube.rotate(3,false);
	faceTest(cube, [
		[
			 [45,1,2]
			,[48,4,5]
			,[51,7,8]
		],[
			 [9,10,11]
			,[12,13,14]
			,[15,16,17]
		],[
			 [18,19,42]
			,[21,22,39]
			,[24,25,36]
		],[
			 [29,32,35]
			,[28,31,34]
			,[27,30,33]
		],[
			 [0,37,38]
			,[3,40,41]
			,[6,43,44]
		],[
			 [26,46,47]
			,[23,49,50]
			,[20,52,53]
		]
	],true);
});
